version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12

jobs:
  deploy:
    executor: my-executor

    steps:
      - checkout

      - run:
          name: npm install
          command: cd functions && npm install

      - run:
          name: set slack webhook URL
          command: npx firebase functions:config:set slack.url=$SLACK_URL

      - run:
          name: set slack channel ID
          command: cd functions && ./node_modules/.bin/firebase functions:config:set slack.channelid=$SLACK_CHANNELID    

      - run:
          name: build & deploy with firebase
          command: cd functions && ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
              
workflows:
  version: 2

  build_test_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
