version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12

jobs:
  deploy:
    executor: my-executor

    steps:
      - checkout

      - run:
          name: npm install
          command: cd functions && npm install

      - run:
          name: build & deploy with firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
              
workflows:
  version: 2

  build_test_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master